CREATE TABLE IF NOT EXISTS dice (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    sides INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS rolls (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    die_id INTEGER,
    value INTEGER,
    FOREIGN KEY (die_id) REFERENCES dice(id)
);
