CREATE TABLE IF NOT EXISTS dice_set (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS dice (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    sides INTEGER NOT NULL,
    set_id INTEGER,
    FOREIGN KEY (set_id) REFERENCES dice_set(id)
);

CREATE TABLE IF NOT EXISTS roll (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    die_id INTEGER,
    value INTEGER,
    FOREIGN KEY (die_id) REFERENCES dice(id)
);
